_wandb:
    value:
        cli_version: 0.26.0
        e:
            3nh0lhwd4isnqolmkbvuliuy9ztbp372:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "126560890880"
                email: adam.mouedden@gmail.com
                executable: /home/adamant/PROJECTS/Singularity/.venv/bin/python3
                git:
                    commit: 57ab431cb3fd8284e5fbe569ac36c58fbd8377e6
                    remote: https://github.com/Adammouedden/Singularity.git
                gpu: NVIDIA GeForce RTX 4060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060
                      uuid: GPU-ef76b5e9-070a-d604-d200-cd7ab00a0590
                host: Cyberpower-AM
                memory:
                    total: "16680931328"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: -m reasoning.singularis.training.train_Singularis
                python: CPython 3.12.3
                root: /home/adamant/PROJECTS/Singularity
                startedAt: "2026-04-16T10:14:01.998613Z"
                writerId: 3nh0lhwd4isnqolmkbvuliuy9ztbp372
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.26.0
            "6": 5.6.0.dev0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 8
datasets:
    value:
        - gsm8k
        - arc-easy
        - arc-challenge
epochs:
    value: 50
frozen:
    value:
        - encoder
        - decoder
lr:
    value: 0.001
max_length:
    value: 128
optimizer:
    value: AdamW
patience:
    value: 7
trainable:
    value:
        - urm_bridge
