_wandb:
    value:
        cli_version: 0.26.0
        e:
            hutgc0d8ep2dh94x3eqcdrw91bfdkwfd:
                cpu_count: 13
                cpu_count_logical: 26
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "253055008768"
                        used: "63822295040"
                email: adam.mouedden@gmail.com
                executable: /content/Singularity/.venv/bin/python3
                git:
                    commit: 57ab431cb3fd8284e5fbe569ac36c58fbd8377e6
                    remote: https://github.com/Adammouedden/Singularity.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-89ff4d80-9ca0-b2a3-1d7c-cd4f633963d5
                host: 566343d7fa49
                memory:
                    total: "247012605952"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.12.13
                root: /content/Singularity
                startedAt: "2026-04-16T10:32:27.240376Z"
                writerId: hutgc0d8ep2dh94x3eqcdrw91bfdkwfd
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.13
            "5": 0.26.0
            "6": 5.6.0.dev0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 8
datasets:
    value:
        - gsm8k
        - arc-easy
        - arc-challenge
epochs:
    value: 50
frozen:
    value:
        - encoder
        - decoder
gradient_checkpointing:
    value: true
lr:
    value: 0.001
max_length:
    value: 128
optimizer:
    value: AdamW
patience:
    value: 7
trainable:
    value:
        - urm_bridge
